---
resources:
  - ../../base
  - distributed-workloads.yaml
  - namespace.yaml
  - llama-cpp-runtime-template.yaml
  - model-catalog-unmanaged-sources.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: dsc-cr.yaml
  - path: odh-dashboard.yaml
