# list of operators
operators:
  # storage odf
  - name: odf-operator
    namespace:
      name: openshift-storage
      create: true
      global: false
    channels: [stable-4.18] # v0,1
    version: "4.18.1-rhodf" # v1
    catalog: openshift-redhat-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: false

  # storage lvms
  - name: lvms-operator
    namespace:
      name: openshift-storage
      create: true
    channels: [stable-4.18] # v0,1
    version: "4.18.2" # v1
    catalog: openshift-redhat-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: true

  # efs
  - name: aws-efs-csi-driver-operator
    namespace:
      name: openshift-cluster-csi-drivers
      create: true
      global: true
    channels: [stable] # v0,1
    version: "4.19.0" # v1
    catalog: openshift-redhat-operators #v1
    source: redhat-operators # v0
    sourceNamespace: openshift-marketplace # v0
    enabled: true
