apiVersion: v1
kind: Service
metadata:
  labels:
    app: undertow-servlet
    app.kubernetes.io/component: undertow-servlet
    app.kubernetes.io/instance: undertow-servlet
  name: {{ .Values.application_name }}
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: 172.30.196.159
  clusterIPs:
  - 172.30.196.159
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    deployment: undertow-servlet
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}