apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: ${MACHINE_SET_NAME} # sno-rpvxz-worker-us-east-2b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: ${CLUSTER_ID} # sno-rpvxz
spec:
  replicas: 0
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: ${CLUSTER_ID} # sno-rpvxz
      machine.openshift.io/cluster-api-machineset: ${MACHINE_SET_NAME} # sno-rpvxz-worker-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: ${CLUSTER_ID} # sno-rpvxz
        machine.openshift.io/cluster-api-machine-role: ${ROLE} # worker
        machine.openshift.io/cluster-api-machine-type: ${ROLE} # worker
        machine.openshift.io/cluster-api-machineset: ${MACHINE_SET_NAME} # sno-rpvxz-worker-us-east-2b
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: ${ROLE}-user-data # worker
          placement:
            availabilityZone: ${AWS_AZ}    # us-east-2b
            region: ${AWS_DEFAULT_REGION}  # us-east-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: ${INSTANCE_TYPE}
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: ${VOLUME_SIZE}
                volumeType: gp3
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - ${SG_NODE} # sno-rpvxz-node
            - filters:
                - name: 'tag:Name'
                  values:
                    - ${SG_LB} # sno-rpvxz-lb
          kind: AWSMachineProviderConfig
          metadataServiceOptions: {}
          tags:
            - name: kubernetes.io/cluster/sno-rpvxz
              value: owned
            - name: description
              value: Product Development and Demo environment for OpenShift
            - name: owner
              value: ateam@acme.com
            - name: team
              value: ateam
            - name: usage
              value: Dev
          deviceIndex: 0
          ami:
            id: ${AWS_AMI} # ami-078e26f293629fe91
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - ${SUBNET_PRIVATE} # sno-rpvxz-subnet-private-us-east-2b
          apiVersion: machine.openshift.io/v1beta1
          iamInstanceProfile:
            id: ${IAM_PROFILE}  # sno-rpvxz-worker-profile
