---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    olm.managed: "true"
  name: nfd-master
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/status
  verbs:
  - get
  - patch
  - update
  - list
- apiGroups:
  - nfd.openshift.io
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  - nodefeaturerules
  - nodefeaturegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nfd.openshift.io
  resources:
  - nodefeaturegroup/status
  verbs:
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - nfd-master.nfd.kubernetes.io
  resources:
  - leases
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    olm.managed: "true"
  name: nfd-worker
  namespace: openshift-nfd
rules:
- apiGroups:
  - nfd.openshift.io
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - get
  - create
  - update
  - delete
- apiGroups:
  - nfd.openshift.io
  resources:
  - nodefeatures/finalizers
  verbs:
  - update
  - get
  - create
  - delete
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nfd-worker
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - policy
  resourceNames:
  - nfd-worker
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
