---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etx-ai-app-of-apps
  namespace: openshift-gitops
  labels:
    rht-gitops.com/openshift-gitops: policies
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: infra/app-of-apps/sno
    directory:
      include: "*.yaml"
    repoURL: https://github.com/redhat-ai-services/etx-agentic-ai.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Validate=true
