---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fast-mcp-tools
  labels:
    app: fast-mcp-tools
spec:
  selector:
    matchLabels:
      app: fast-mcp-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: fast-mcp-tools
        deployment: fast-mcp-tools
    spec:
      serviceAccountName: fast-mcp-tools
      containers:
      - name: fast-mcp-tools
        image: quay.io/eformat/fast-mcp-tools:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        resources: {}
