---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fast-mcp-tools
subjects:
  - kind: ServiceAccount
    name: fast-mcp-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
