---
apiVersion: v1
kind: Service
metadata:
  name: fast-mcp-tools
  labels:
    app: fast-mcp-tools
spec:
  selector:
    app: fast-mcp-tools
    deployment: fast-mcp-tools
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
