---
apiVersion: v1
kind: Pod
metadata:
  name: download-model
spec:
  volumes:
    - name: model-volume
      persistentVolumeClaim:
        claimName: $PVC_CLAIM_NAME
  restartPolicy: Never
  initContainers:
    - name: fix-volume-permissions
      image: registry.access.redhat.com/ubi9/ubi-micro:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      command: ["sh"]
      args: ["-c", "mkdir -p /mnt/$MODEL_PATH && chmod -R 777 /mnt"]
      volumeMounts:
        - mountPath: "/mnt"
          name: model-volume
  containers:
    - name: download-model
      image: registry.access.redhat.com/ubi9/python-311:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: true
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "12Gi"
          cpu: "1"
      command: ["sh"]
      args:
        [
          "-c",
          "pip install --upgrade pip && pip install --upgrade huggingface_hub && python3 -c 'from huggingface_hub import snapshot_download\nsnapshot_download(\n repo_id=\"${MODEL}\",\nlocal_dir=\"/mnt/$MODEL_PATH\",local_dir_use_symlinks=False,use_auth_token=\"${HF_TOKEN}\")'",
        ]
      volumeMounts:
        - mountPath: "/mnt"
          name: model-volume
      env:
        - name: TRANSFORMERS_CACHE
          value: /tmp
