---
apiVersion: maistra.io/v1
kind: ServiceMeshMemberRoll
metadata:
  name: default
  namespace: istio-system
spec:
  members:
  - knative-serving
  - redhat-ods-applications-auth-provider
  - rhoai-model-registries
  - vllm-server
  - agent-demo
